#include <stdio.h>
#include <cs50.h>
#include <string.h> //Needed for 'strlen'
#include <ctype.h>
#include <unistd.h>
#include <crypt.h>
#define _XOPEN_SOURCE

void match(string pwd, string salt, string hash);

int main(int argc, string argv[])
{
    // If the program is run without exactly 1 argument, exit program with error
    if(argc != 2)
    {
        printf("Usage: ./crack [hash]\n");
        return 1;
    }
    else
    {
        // User inputs a hash at the cmd line
        string hash = argv[1];
        
        // Salt is actually the first 2 characters of the hash
        char salt[] = { hash[0], hash[1], '\0' };
        
        //Empty array of passwords that we will try later. Initialized w/ NULL characters to eliminate undefined behavior
        char pwd[5];
        memset(pwd,'\0',sizeof(pwd));
        
        //Empty array to store the upper and lower case alphabet. Initialized w/ NULL characters to eliminate undefined behavior
        char alphabet[54];
        memset(alphabet,'\0',sizeof(alphabet));
        
         // Fill 'alphabet' with all upper and lower case letters
        for (int i=0;i<26;i++)
        {
            alphabet[i]   =  (char)(i+65);
            alphabet[i+26]  =  (char)(i+97);
        }

        // Try all possible 1-, 2-, 3-, and 4- character passwords
        for (int n=0;n<53;n++)
        {
            for (int i=0;i<53;i++)
            {
                for (int j=0;j<53;j++)
                {
                    for (int p=0;p<52;p++)
                    {
                        pwd[0]=alphabet[p];
                        match(pwd,salt,hash); // Check for a match between user hash and generated hash
                    }
                    pwd[0]='A';
                    pwd[1]=alphabet[j];
                }
                pwd[1]='A';
                pwd[2]=alphabet[i];
            }
            pwd[2]='A';
            pwd[3]=alphabet[n];   
        }
        return 0;
    }
    
}

// This function compares the input hash given at the cmd prompt with the hash generated by the nested FOR loops above. If there is a match it prints the password and exits the program.
void match(string pwd, string salt, string hash)
{
    if(strcmp(crypt(pwd,salt),hash)==0)
        {
            printf("%s\n",pwd); // If the 2 hashes match, print password
            exit(0);            // exit if match
        }
}